name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main  # Tự động chạy mỗi khi bạn push code vào nhánh main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Connect to AWS and Run Deploy Script
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          # Bơm toàn bộ nội dung file deploy.sh từ máy ảo GitHub vào thẳng server AWS để thực thi
          script_stop_on_error: true
          script: |
            bash -s < deploy.sh
